### ISSUE TITLE
TypeError: ('Shape must be integers', TensorConstant{[  4.   6... 24.  -1.]}, 'float64')

### ISSUE THREAD

**Issue by watsonyanghx** [FredericGodin/DynamicCNN#1]
hello,I'm new to CNN and NLP, I read the paper you mentioned in the repo, and i want to run this program to see how it process, but it gives the error as bellows:

> "D:\Program Files\Anaconda3\python.exe" "D:/Program Files (x86)/JetBrains/PycharmProjects/fir_PyPrj/trainDCNN.py"
> WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
> ERROR (theano.sandbox.cuda): nvcc compiler not found on $PATH. Check your nvcc installation and try again.
> Hyperparameters: {'adagrad_reset': 5, 'word_vector_size': 48, 'learning_rate': 0.1, 'vocab_size': 15448, 'output_classes': 2, 'nr_of_filters_conv_layers': [6, 14], 'dropout_value': 0.5, 'activations': ['tanh', 'tanh'], 'batch_size': 4, 'filter_size_conv_layers': [7, 5], 'valid_freq': 10, 'ktop': 4, 'n_epochs': 500, 'L2': [5e-05, 1.5e-05, 1.5e-06, 5e-05]}
> Loading the training data
> Building the model
> Traceback (most recent call last):
>   File "D:/Program Files (x86)/JetBrains/PycharmProjects/fir_PyPrj/trainDCNN.py", line 90, in <module>
>     loss_train = lasagne.objectives.aggregate(lasagne.objectives.categorical_crossentropy(lasagne.layers.get_output(output_layer,X_batch),y_batch),mode='mean')+lasagne.regularization.regularize_layer_params_weighted(dict(zip(l2_layers,hyperparas["L2"])),lasagne.regularization.l2)
>   File "D:\Program Files\Anaconda3\lib\site-packages\lasagne\layers\helper.py", line 191, in get_output
>     all_outputs[layer] = layer.get_output_for(layer_inputs, *_kwargs)
>   File "D:\Program Files (x86)\JetBrains\PycharmProjects\fir_PyPrj\DCNN\folding.py", line 27, in get_output_for
>     folded_output = T.reshape(summed,(self.input_shape[0], self.input_shape[1],self.input_shape[2]/2, -1))
>   File "D:\Program Files\Anaconda3\lib\site-packages\theano\tensor\basic.py", line 4541, in reshape
>     rval = op(x, newshape)
>   File "D:\Program Files\Anaconda3\lib\site-packages\theano\gof\op.py", line 611, in **call**
>     node = self.make_node(_inputs, **kwargs)
>   File "D:\Program Files\Anaconda3\lib\site-packages\theano\tensor\basic.py", line 4363, in make_node
>     raise TypeError("Shape must be integers", shp, shp.dtype)
> TypeError: ('Shape must be integers', TensorConstant{[  4.   6... 24.  -1.]}, 'float64')
> Process finished with exit code 1

I run it on the pycharm on windows8.1, i don't know where is wrong, could you please help me?Thank you every much!

**Comment by FredericGodin** [comment]
Dear DavorWade,

this is a Theano installation issue and has nothing to do with the example code.
I suggest you take a look at the Theano installation instructions.

Best,

Fréderic

**Comment by watsonyanghx** [comment]
Thanks for you kind help, i try it on ubuntu 14.04 and the theano&lasagne both are running well, but i still get the error showed bellow:

> /home/ubuntu/anaconda3/bin/python /home/ubuntu/PycharmProjects/DynamicCNN/trainDCNN.py
> Using gpu device 0: GeForce GT 755M (CNMeM is disabled, CuDNN 4007)
> Hyperparameters: {'L2': [5e-05, 1.5e-05, 1.5e-06, 5e-05], 'dropout_value': 0.5, 'activations': ['tanh', 'tanh'], 'nr_of_filters_conv_layers': [6, 14], 'learning_rate': 0.1, 'batch_size': 4, 'filter_size_conv_layers': [7, 5], 'n_epochs': 500, 'adagrad_reset': 5, 'valid_freq': 10, 'vocab_size': 15448, 'ktop': 4, 'word_vector_size': 48, 'output_classes': 2}
> Loading the training data
> Building the model
> /home/ubuntu/anaconda3/lib/python3.5/site-packages/lasagne/init.py: 100: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
>   low=self.range[0], high=self.range[1], size=shape))
> /home/ubuntu/anaconda3/lib/python3.5/site-packages/numpy/core/numeric.py:190: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
>   a = empty(shape, dtype, order)
> Traceback (most recent call last):
>   File "/home/ubuntu/PycharmProjects/DynamicCNN/trainDCNN.py", line 90, in <module>
>     loss_train = lasagne.objectives.aggregate(lasagne.objectives.categorical_crossentropy(lasagne.layers.get_output(output_layer,X_batch),y_batch),mode='mean')+lasagne.regularization.regularize_layer_params_weighted(dict(zip(l2_layers,hyperparas["L2"])),lasagne.regularization.l2)
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/lasagne/layers/helper.py", line 191, in get_output
>     all_outputs[layer] = layer.get_output_for(layer_inputs, *_kwargs)
>   File "/home/ubuntu/PycharmProjects/DynamicCNN/DCNN/folding.py", line 27, in get_output_for
>     folded_output = T.reshape(summed,(self.input_shape[0], self.input_shape[1],self.input_shape[2]/2, -1))
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/theano/tensor/basic.py", line 4543, in reshape
>     rval = op(x, newshape)
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/theano/gof/op.py", line 613, in **call**
>     node = self.make_node(_inputs, **kwargs)
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/theano/tensor/basic.py", line 4365, in make_node
>     raise TypeError("Shape must be integers", shp, shp.dtype)
> TypeError: ('Shape must be integers', TensorConstant{[  4.   6... 24.  -1.]}, 'float64')
> Process finished with exit code 1

it gives

> TypeError: ('Shape must be integers', TensorConstant{[  4.   6... 24.  -1.]}, 'float64')

caused by "trainDCNN.py", line 90" and "folding.py", line 27". I don't know where is  wrong, could you give me some help? Thank you very much!
