### ISSUE TITLE
How to construct the data set?

### ISSUE THREAD

**Issue by patatoCC8745** [FredericGodin/DynamicCNN#14]
Hello, I want to ask you a question. Do you know how did the authors of this paper construct such data set? I have downloaded their SST_binary.mat file. And I am confused how they get the train, valid and test files from the index file. When I try to transferred the numbers of each row to the English words according to the index file, I find that I can't always get the complete or meaningful sentences from each row. Sometimes I will get a sentence, sometimes get the words, and sometimes get some meaningless phrases. So I want to ask how do the authors construct this data set?

**Comment by FredericGodin** [comment]
The splits are standard splits used for this dataset. You can find a reference in the paper. 
This dataset contains subphrases too that have been annotated.

Note that this is not an issue related to this project so I'm closing it.

**Comment by patatoCC8745** [comment]
OK，Thank you.
