### ISSUE TITLE
'Shape must be integers', TensorConstant{[  4.   6... 24.  -1.]}, 'float64'

### ISSUE THREAD

**Issue by watsonyanghx** [FredericGodin/DynamicCNN#2]
I'm sorry to disturb you again, after successfully installing the theano and lasagne, i try it on ubuntu 14.04 and the theano&lasagne both are running well, but i still get the error showed bellow:

> /home/ubuntu/anaconda3/bin/python /home/ubuntu/PycharmProjects/DynamicCNN/trainDCNN.py
> Using gpu device 0: GeForce GT 755M (CNMeM is disabled, CuDNN 4007)
> Hyperparameters: {'L2': [5e-05, 1.5e-05, 1.5e-06, 5e-05], 'dropout_value': 0.5, 'activations': ['tanh', 'tanh'], 'nr_of_filters_conv_layers': [6, 14], 'learning_rate': 0.1, 'batch_size': 4, 'filter_size_conv_layers': [7, 5], 'n_epochs': 500, 'adagrad_reset': 5, 'valid_freq': 10, 'vocab_size': 15448, 'ktop': 4, 'word_vector_size': 48, 'output_classes': 2}
> Loading the training data
> Building the model
> /home/ubuntu/anaconda3/lib/python3.5/site-packages/lasagne/init.py: 100: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
>   low=self.range[0], high=self.range[1], size=shape))
> /home/ubuntu/anaconda3/lib/python3.5/site-packages/numpy/core/numeric.py:190: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
>   a = empty(shape, dtype, order)
> Traceback (most recent call last):
>   File "/home/ubuntu/PycharmProjects/DynamicCNN/trainDCNN.py", line 90, in <module>
>     loss_train = lasagne.objectives.aggregate(lasagne.objectives.categorical_crossentropy(lasagne.layers.get_output(output_layer,X_batch),y_batch),mode='mean')+lasagne.regularization.regularize_layer_params_weighted(dict(zip(l2_layers,hyperparas["L2"])),lasagne.regularization.l2)
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/lasagne/layers/helper.py", line 191, in get_output
>     all_outputs[layer] = layer.get_output_for(layer_inputs, *_kwargs)
>   File "/home/ubuntu/PycharmProjects/DynamicCNN/DCNN/folding.py", line 27, in get_output_for
>     folded_output = T.reshape(summed,(self.input_shape[0], self.input_shape[1],self.input_shape[2]/2, -1))
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/theano/tensor/basic.py", line 4543, in reshape
>     rval = op(x, newshape)
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/theano/gof/op.py", line 613, in **call**
>     node = self.make_node(_inputs, **kwargs)
>   File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/theano/tensor/basic.py", line 4365, in make_node
>     raise TypeError("Shape must be integers", shp, shp.dtype)
> TypeError: ('Shape must be integers', TensorConstant{[  4.   6... 24.  -1.]}, 'float64')
> Process finished with exit code 1

it gives

> TypeError: ('Shape must be integers', TensorConstant{[  4.   6... 24.  -1.]}, 'float64')

caused by "trainDCNN.py", line 90" and "folding.py", line 27". I don't know where is  wrong, could you give me some help? Thank you very much!

**Comment by FredericGodin** [comment]
I don't know exactly but are you running the code on GPU using the correct Theano flags?
Normally, there shouldn't be "float64" messages in there.
THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32 python train.py

http://deeplearning.net/software/theano/tutorial/using_gpu.html

**Comment by watsonyanghx** [comment]
Thans for your reply. I test the theano following the step http://deeplearning.net/software/theano/tutorial/using_gpu.html#testing-theano-with-gpu , and the result is the same with it, meaning the theano is successfully installed and is using the GPU. But when i run the command as you give 

> THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32 python trainDCNN.py

it still gives me the same error message. I'm using Anaconda python 3.5, and the version of theano is 0.8.0, the lasagne is 0.2.dev1, does the error have something to do with the version?

**Comment by FredericGodin** [comment]
I'm using the same version of Theano and Lasagne. I do use Python 2.7.

I possible issue could be the division on line 27. Integer divisions are done differently in Python 2.7/3.5.

Replace line 27 in folding.py with:
folded_output = T.reshape(summed,(self.input_shape[0], self.input_shape[1],T.cast(self.input_shape[2]/2,"int32"), -1))

**Comment by watsonyanghx** [comment]
@FredericGodin  Thank you very much for your kind help! After I change the python version to 2.7 and it works well now. But it still gives some errors when i use python 3.5, so i think it's the version that matters. Again, thank you for you kind help!

**Comment by pklfz** [comment]
Address this issue in Python3.5:
Additionally, cast expression of Line 14 in folding.py and Line 55 61 68 in trainDCNN.py as Integer like int(...)

**Comment by FredericGodin** [comment]
Hey,
I'm not planning to support Python 3. Feel free to do so ;)
