### ISSUE TITLE
How to transform the output of K-max pooling to sentence vector which is used to classification

### ISSUE THREAD

**Issue by lixin4ever** [FredericGodin/DynamicCNN#3]
Hi Godin,

According to the paper, the convolution operation will not change "number of rows" of feature map while folding will halve the row number. 
I saw two folding layers in you implementation and the initial dimension of embedding is 48 (i.e., row number of 1st convolution layer's output), 
after two pooling layer, the row number of feature map should be 12, 
I wonder how you transform these feature maps to the top sentence vector. (It seems that author does not give answer in this paper)

Look forward to your reply

**Comment by FredericGodin** [comment]
Indeed, after a couple of folds, the dimension will be 12.
Next, you can flatten that 3D matrix in a 2D matrix.
That's what happens in the DenseLayer: http://lasagne.readthedocs.org/en/latest/modules/layers/dense.html

As written in the notes:

> Notes
> 
> If the input to this layer has more than two axes, it will flatten the trailing axes. This is useful for when a dense layer follows a convolutional layer, for example. It is not necessary to insert a FlattenLayer in this case.
