### ISSUE TITLE
what is the number "15448" mean in dataset

### ISSUE THREAD

**Issue by 333caowei** [FredericGodin/DynamicCNN#4]
Hi FredericGodin, thanks for your code about DynamicCNN, I saw that in dataset, there are to many "15448" at each end of sentences, What's this mean?

**Comment by FredericGodin** [comment]
Hi,
That's the padding symbol to fill up the matrix.
There are 15448 words/tokens in de dataset (indexes 0->15447) and number "15448" is the padding symbol.

**Comment by 333caowei** [comment]
Do you still have the source code for get  Labelled phrases that occur as subparts of the training sentences? In your Repositories only have training data directly, but no the source code of how to get the subparts of the training sentences in training data.

**Comment by FredericGodin** [comment]
No I don't have it, I used the Matlab file provided by the orignal authors on their website...
You can reconstruct it if you you use the code from Stanford.

**Comment by rpandey4** [comment]
Can you please elaborate more, on what basis the padding is done

**Comment by FredericGodin** [comment]
Don't know exactly what you mean..
I believe the answer would be the maximum sentence length. 
Theano wants a fixed-size matrix as input but many sentences are much smaller so you pad them with a padding symbol until you reach the maximum sentence length.

**Comment by rpandey4** [comment]
Okay I understood, I was confused that each padded input is not having the same length.

Thank you
