### ISSUE TITLE
The original data set

### ISSUE THREAD

**Issue by richliao** [FredericGodin/DynamicCNN#5]
Hi Frederic, thanks for posting this awesome work. I have learned a lot. Do you mind post the author website which has source code and dataset? I couldn't find the matlab code you mentioned. Regarding to the dataset in your sample, it seems each array is one sentence, from which how each can form a document? I am seeing label is at sentence level. Or I missed something here? Also each sentence is cap at length 58. What's the original stanford data set? In the paper it said it's IMDB.

**Comment by FredericGodin** [comment]
The code of the author can be found over here: http://phd.nal.co/DCNN
It contains a processed version of the Stanford Dataset. So I didn't do any preprocessing myself.
I don't know exactly anymore what the relation between the components is. It had something to do with this treebank: http://nlp.stanford.edu/sentiment/treebank.html. As you can see, parts of sentences are also annotated with labels.
