### ISSUE TITLE
meaning the numbers 1 and 2 in the data set

### ISSUE THREAD

**Issue by razy** [FredericGodin/DynamicCNN#6]
Hi Frederic, I am still confused about the data set, what does it mean the numbers 2 and 1 contained in the file Test.lbl, train.lbl and valid.lbl. whether it is meaningful to a positive number 1 and number 2 to the negative?

**Comment by FredericGodin** [comment]
I don't know which number is positive or negative but I doesn't matter for training the model of course. It is still a binary classifier.
