### ISSUE TITLE
embedding layer

### ISSUE THREAD

**Issue by junirose** [FredericGodin/DynamicCNN#7]
what is the function of sentenceembeddinglayer? how to use sentences in padding?

**Comment by FredericGodin** [comment]
I created an extension of the standard EmbeddingLayer which contains just an additional non-trainable representation for padding. Depending on what the index is of the padding element, you can add 'first', 'last' or None. The EmbeddingLayer as such is just a matrix for which each row represents a (trainable) representation for a word.

E.g., if you choose to give the padding index '0', then you initialize the padding with value 'first'.

**Comment by junirose** [comment]
if there is a lot of padding what influence the accuracy of the results?

**Comment by FredericGodin** [comment]
I don't know by hard, its been a while since I implemented the code. Also, it's not my paper...
