### ISSUE TITLE
network paras

### ISSUE THREAD

**Issue by junirose** [FredericGodin/DynamicCNN#8]
where the value of 48 obtained in word_vector_size? as well as the value of the filter_size_conv_layers and nr_of_filters_conv_layers.
thank you for your answers

**Comment by FredericGodin** [comment]
Those values were experimentally determined by the authors of the paper (not by me).

**Comment by junirose** [comment]
Hii..
How to display the results of sentiment analysis. Thank you for your help

Pada tanggal 4 Nov 2016 5.26 PM, "Fréderic Godin" <notifications@github.com>
menulis:
